# Generated by Django 6.0.3 on 2026-03-30 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookMark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=512)),
                ('title', models.CharField(max_length=128)),
                ('description', models.CharField(max_length=512)),
                ('summary', models.TextField()),
            ],
        ),
    ]
